### ISSUE TITLE
gitspo.com redirects to https://aboutsnack.com

### ISSUE THREAD

**Issue by R1j1t** [gitspo/gitspo-analytics#8]
**Describe the bug**

**To Reproduce**
1. Go to https://gitspo.com/
2. redirects to https://aboutsnack.com

**Expected behavior**
should be able to visit gitspo website (with dashboard)

**Comment by aleksandr-kotlyar** [comment]
Same problem today. The domain https://gitspo.com/ doesn't work and redirects to https://aboutsnack.com

I can't try GitSpo product.

**Comment by gajus** [comment]
How are you guys still discovering GitSpo?

The project has been largely discontinued.

**Comment by aleksandr-kotlyar** [comment]
> How are you guys still discovering GitSpo?
> 
> The project has been largely discontinued.

It's sad to find out. Project has a very promising description.

**Comment by gajus** [comment]
Unfortunately, there was no viable monetization path for it.

**Comment by R1j1t** [comment]
I understand @gajus as @aleksandr-kotlyar mentioned the use case was interesting. I actually found out about this by [github marketplace](https://github.com/marketplace/gitspo) hence I never thought of it as discontinued

**Comment by aleksandr-kotlyar** [comment]
> How are you guys still discovering GitSpo?
> 
> The project has been largely discontinued.
>
> Unfortunately, there was no viable monetization path for it.

I think this app should be hidden from marketplace in this case.

**Comment by gajus** [comment]
I am currently in talks about selling this app.

It might come back to life in the next month.
